//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstAzureWebApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyFirstAzureWebApp.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงื่อนไขการทำรายการEN.
        /// </summary>
        public static string C_PROCESS {
            get {
                return ResourceManager.GetString("C_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string D_FIRST_NAME {
            get {
                return ResourceManager.GetString("D_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        public static string D_INVALID_SESSION {
            get {
                return ResourceManager.GetString("D_INVALID_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string D_LAST_NAME {
            get {
                return ResourceManager.GetString("D_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string D_NAME1D {
            get {
                return ResourceManager.GetString("D_NAME1D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string D_PASSWORD {
            get {
                return ResourceManager.GetString("D_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Dupplicated.
        /// </summary>
        public static string D_PROS_ACC_DUP {
            get {
                return ResourceManager.GetString("D_PROS_ACC_DUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string D_USER_NAME {
            get {
                return ResourceManager.GetString("D_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูล ชื่อ, เลขผู้เสียภาษี/เลขประจำตัวประชาชน , ตำบล มีอยู่ในระบบแล้ว กรุณาระบุข้อมูลใหม่.
        /// </summary>
        public static string E_0002 {
            get {
                return ResourceManager.GetString("E_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  $P$ .
        /// </summary>
        public static string E_CUSTOM_MSG_ONLY {
            get {
                return ResourceManager.GetString("E_CUSTOM_MSG_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พบข้อผิดพลาดในการลบข้อมูล $P$.
        /// </summary>
        public static string E_DELETE_FAIL {
            get {
                return ResourceManager.GetString("E_DELETE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dupplicate Data Prospect.
        /// </summary>
        public static string E_DUP_DATA_PROSTPECT {
            get {
                return ResourceManager.GetString("E_DUP_DATA_PROSTPECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $P$.
        /// </summary>
        public static string E_EXCEPTION {
            get {
                return ResourceManager.GetString("E_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found $P$ For Approved.
        /// </summary>
        public static string E_FOUND_PLAN_TRIP_APPROVE1 {
            get {
                return ResourceManager.GetString("E_FOUND_PLAN_TRIP_APPROVE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พบข้อผิดพลาดในการเพิ่มข้อมูล $P$.
        /// </summary>
        public static string E_INSERT_FAIL {
            get {
                return ResourceManager.GetString("E_INSERT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName or Password Invalid.
        /// </summary>
        public static string E_INVALID_AUTHENTICATION {
            get {
                return ResourceManager.GetString("E_INVALID_AUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง.
        /// </summary>
        public static string E_INVALID_AUTHENTICATION1 {
            get {
                return ResourceManager.GetString("E_INVALID_AUTHENTICATION1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $P$ - $P$.
        /// </summary>
        public static string E_INVALID_BUSINESS_CUSTOM_MSG {
            get {
                return ResourceManager.GetString("E_INVALID_BUSINESS_CUSTOM_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data $P$ invalid.
        /// </summary>
        public static string E_INVALID_DATA {
            get {
                return ResourceManager.GetString("E_INVALID_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data $P$ Invalid because $P$.
        /// </summary>
        public static string E_INVALID_DATA_WITH_REASON {
            get {
                return ResourceManager.GetString("E_INVALID_DATA_WITH_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found $P$ For Approve.
        /// </summary>
        public static string E_NOT_FOUND_PLAN_TRIP_APPROVE {
            get {
                return ResourceManager.GetString("E_NOT_FOUND_PLAN_TRIP_APPROVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณไม่มีสิทธิ์ใช้ API Service นี้.
        /// </summary>
        public static string E_NOT_PERMISSION {
            get {
                return ResourceManager.GetString("E_NOT_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พบข้อผิดพลาดในการแก้ไขข้อมูล $P$.
        /// </summary>
        public static string E_UPDATE_FAIL {
            get {
                return ResourceManager.GetString("E_UPDATE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t clone prospect : Prospect Not Found.
        /// </summary>
        public static string R_CANNOT_CLONE_PROSPECT {
            get {
                return ResourceManager.GetString("R_CANNOT_CLONE_PROSPECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมดเวลาในการบันทึกรายการEN.
        /// </summary>
        public static string R_SAVE_PERIOD_TIME {
            get {
                return ResourceManager.GetString("R_SAVE_PERIOD_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขตู้น้ำมันและมือจ่ายน้ำมันมีอยู่แล้ว กรุณาระบุข้อมูลใหม่.
        /// </summary>
        public static string W_0001 {
            get {
                return ResourceManager.GetString("W_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถ Approve Plan Trip ได้ เนื่องจากจำนวน Plan Trip ของ Sale Rep ที่สามารถ Approve ได้ต่อวันครบแล้ว.
        /// </summary>
        public static string W_0004 {
            get {
                return ResourceManager.GetString("W_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถ Merge Plan Trip ได้เนื่องจากไม่มี Plan Trip ที่ได้รับการ Approve หรือไม่พบ Plan Trip หลัก.
        /// </summary>
        public static string W_0005 {
            get {
                return ResourceManager.GetString("W_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณายืนยันข้อมูล เนื่องจากข้อมูลน้อยกว่าค่า % Over Range.
        /// </summary>
        public static string W_0006 {
            get {
                return ResourceManager.GetString("W_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณายืนยันข้อมูล เนื่องจากข้อมูลมากกว่าค่า % Over Range.
        /// </summary>
        public static string W_0007 {
            get {
                return ResourceManager.GetString("W_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถทำการ Clone Prospect ได้ เนื่องจากมีใน BU ของท่านแล้ว ใน Territory $P$.
        /// </summary>
        public static string W_0012 {
            get {
                return ResourceManager.GetString("W_0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospect/Customer ซ้ำใน Approved Plan.
        /// </summary>
        public static string W_0013 {
            get {
                return ResourceManager.GetString("W_0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลซ้ำ กรุณาระบุข้อมูลใหม่อีกครั้ง.
        /// </summary>
        public static string W_0014 {
            get {
                return ResourceManager.GetString("W_0014", resourceCulture);
            }
        }
    }
}
