CREATE TABLE dbo.Table_2
	(
	Id int NOT NULL,
	Name varchar(50) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Table_2 ADD CONSTRAINT
	PK_Table_2 PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO